online-pharmacy/cse471/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online-pharmacy/online-pharmacy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('shop/', include('shop.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online-pharmacy/shop/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", views.index, name="ShopHome"),
    path("login/", views.Login, name="LogIn"),
    path("signup/", views.signup, name="SignUp"),
    path("logout/", views.Logout, name="Logout"),
    path("about/", views.about, name="AboutUs"),
    path("help/", views.help, name="Help"),
    path("contact/", views.contact, name="ContactUs"),
    path("search/", views.search, name="Search"),
    path("nomatch/", views.search, name="nomatch"),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path("checkout/", views.checkout, name="Checkout"),
    path("prescribed/", views.prescribed, name="prescribed"),
    path("otc/", views.otc, name="otc"),
    path("healthcare/", views.healthcare, name="healthcare"),
    path("pharmacist/", views.pharmacist, name="Pharmacist"),
    path("payment/", views.payment, name="payment"),
    path('profile/', views.profile, name='profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('profile_view/', views.profile_view, name='profile_view'),
]

urlpatterns += staticfiles_urlpatterns()

online-pharmacy/shop/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    product_id = models.AutoField
    product_name = models.CharField(max_length=20)
    category = models.CharField(max_length=20, default="")
    subcategory = models.CharField(max_length=20, default="")
    price = models.IntegerField(default=0)
    desc = models.CharField(max_length=1000)
    pub_date = models.DateField()
    image = models.ImageField(upload_to="shop/images", default="/default.jpg")
    available_pharmacies = models.ManyToManyField(User, related_name='available_products', blank=True)

    def __str__(self):
        return self.product_name


class UserProfile(models.Model):
    USER_ROLES = [
        ('Customer', 'Customer'),
        ('Pharmacist', 'Pharmacist'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=50, choices=USER_ROLES, default='Customer')
    image = models.ImageField(upload_to='profile_pics/', default='')
    full_name = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=50, blank=True, null=True)
    area = models.CharField(max_length=20, blank=True, null=True)
    contact_number = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return f"{self.user.username} - {self.role}"

    def get_area(self):
        return self.area

online-pharmacy/shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile
from .models import Product
# shop/forms.py

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from .models import UserProfile

class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

class UserProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['image', 'full_name', 'address', 'area', 'contact_number']

class CreateUserForm(UserCreationForm):
    ROLE_CHOICES = [
        ('Customer', 'Customer'),
        ('Pharmacist', 'Pharmacist'),
    ]
    role = forms.ChoiceField(choices=ROLE_CHOICES, required=True)
    image = forms.ImageField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'role', 'image']


class ProductForm(forms.ModelForm):
    CATEGORY_CHOICES = [
        ('Prescribed Medicines', 'Prescribed Medicines'),
        ('OTC Medicines', 'OTC Medicines'),
        ('Healthcare Products', 'Healthcare Products'),
    ]

    category = forms.ChoiceField(choices=CATEGORY_CHOICES)

    class Meta:
        model = Product
        fields = ['product_name', 'category', 'subcategory', 'price', 'desc', 'image']

online-pharmacy/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Product, UserProfile
from django.contrib import messages
from math import ceil
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm, ProductForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from datetime import date
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm, UserProfileUpdateForm
from django.contrib.auth import update_session_auth_hash
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import CustomPasswordChangeForm

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Product, UserProfile
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.db.models import Q

def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == "POST":
        if request.user.is_authenticated:
            if 'available' in request.POST:
                if request.user not in product.available_pharmacies.all():
                    product.available_pharmacies.add(request.user)
                    
                else:
                    messages.info(request, 'You are already marked as available for this product.')
            elif 'not_available' in request.POST:
                if request.user in product.available_pharmacies.all():
                    product.available_pharmacies.remove(request.user)
                    
                else:
                    messages.info(request, 'You are already marked as not available for this product.')
            return redirect('product_detail', product_id=product.id)
        else:
            messages.error(request, 'You need to be logged in to perform this action.')

    available_pharmacies = product.available_pharmacies.all()

    print(available_pharmacies)

    pharmacies_with_area = [
        {
            "pharmacy": pharmacy,
            "area": pharmacy.userprofile.area if hasattr(pharmacy, 'userprofile') else "N/A"
        }
        for pharmacy in available_pharmacies
    ]

    context = {
        'product': product,
        'available_pharmacies': available_pharmacies,
        'pharmacies_with_area': pharmacies_with_area,
        'user_role': request.user.userprofile.role if request.user.is_authenticated else None,
    }

    return render(request, 'shop/product.html', context)

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        try:
            profile_instance = request.user.userprofile
        except UserProfile.DoesNotExist:
            profile_instance = None

        p_form = UserProfileUpdateForm(request.POST, request.FILES, instance=profile_instance)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            if p_form:
                profile = p_form.save(commit=False)
                profile.user = request.user
                profile.save()
            messages.success(request, 'Your account has been updated!')
            return redirect('/shop/profile_view')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        u_form = UserUpdateForm(instance=request.user)
        try:
            profile_instance = request.user.userprofile
        except UserProfile.DoesNotExist:
            profile_instance = None

        p_form = UserProfileUpdateForm(instance=profile_instance)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'shop/profile.html', context)


@login_required
def profile_view(request):
    user = request.user
    profile = get_object_or_404(UserProfile, user=user)
    
    context = {
        'user': user,
        'profile': profile,
    }
    return render(request, 'shop/profile_view.html', context)

@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user) 
            messages.success(request, 'Your password was successfully updated!')
            return redirect('/shop/profile') 
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = CustomPasswordChangeForm(request.user)
    return render(request, 'shop/change_password.html', {'form': form})


def Login(request):
    if request.user.is_authenticated:
        return redirect('/shop')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('/shop')
            else:
                messages.info(request, 'Wrong Username or Password')

        context = {}
        return render(request, 'shop/login.html', context)

def signup(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            role = form.cleaned_data.get('role')
            image = form.cleaned_data.get('image')
            UserProfile.objects.create(user=user, role=role, image=image)
            messages.success(request, 'Your Account Has Been Created')
            return redirect('/shop/login')
    else:
        form = CreateUserForm()
    context = {'form': form}
    return render(request, 'shop/signup.html', context)

def index(request):
    role = None
    if request.user.is_authenticated:
        try:
            user_profile = UserProfile.objects.get(user=request.user)
            role = user_profile.role
        except ObjectDoesNotExist:
            pass

    products = Product.objects.all()
    listAll = []
    listCat = Product.objects.values('category').distinct()
    allCat = {item['category'] for item in listCat}
    for cat in allCat:
        items = Product.objects.filter(category=cat)
        x = len(items)
        slideN = x // 4 + ceil((x / 4 - (x // 4)))
        listAll.append([items, range(1, slideN), slideN])

    if request.method == "POST":
        product_id = request.POST.get('product_id')
        try:
            product = Product.objects.get(id=product_id)
            if 'available' in request.POST:
                if request.user not in product.available_pharmacies.all():
                    product.available_pharmacies.add(request.user)
                    
                else:
                    messages.info(request, 'You are already marked as available for this product.')
            elif 'not_available' in request.POST:
                if request.user in product.available_pharmacies.all():
                    product.available_pharmacies.remove(request.user)
                    
                else:
                    messages.info(request, 'You are already marked as not available for this product.')

            # Redirect after successful form submission to prevent refresh issues
            return HttpResponseRedirect(request.path_info)

        except Product.DoesNotExist:
            messages.error(request, 'Product not found.')

    context = {'listAll': listAll, 'role': role, 'is_authenticated': request.user.is_authenticated}
    return render(request, 'shop/index.html', context)
def Logout(request):
    logout(request)
    return redirect('/shop/login')

def about(request):
    return render(request, 'shop/about.html')

def help(request):
    return render(request, 'shop/help.html')

def contact(request):
    return render(request, 'shop/contact.html')

def payment(request):
    return render(request, 'shop/payment.html')

def search(request):
    keyword = request.GET.get('search')
    listAll = []
    listCat = Product.objects.values('category').distinct()
    allCat = {item['category'] for item in listCat}

    for cat in allCat:
        items = Product.objects.filter(category=cat).filter(Q(product_name__icontains=keyword))
        x = len(items)
        slideN = x // 4 + ceil((x / 4 - (x // 4)))
        listAll.append([items, range(1, slideN), slideN])

    if len(listAll) == 0:
        return render(request, 'shop/nomatch.html')

    if request.method == "POST" and request.user.is_authenticated:
        product_id = request.POST.get('product_id')
        try:
            product = Product.objects.get(id=product_id)

            if 'available' in request.POST:
                if request.user not in product.available_pharmacies.all():
                    product.available_pharmacies.add(request.user)
                    messages.success(request, 'Marked as available for this product.')
                else:
                    messages.info(request, 'You are already marked as available for this product.')

            elif 'not_available' in request.POST:
                if request.user in product.available_pharmacies.all():
                    product.available_pharmacies.remove(request.user)
                    messages.success(request, 'Marked as not available for this product.')
                else:
                    messages.info(request, 'You are already marked as not available for this product.')

            # Redirect after successful form submission to prevent refresh issues
            return HttpResponseRedirect(request.path_info)

        except Product.DoesNotExist:
            messages.error(request, 'Product not found.')

online-pharmacy/shop/templates/shop/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <style>
        body {
            color: #fff;
            background: linear-gradient(to right, #adf5ee, #0ba797);
            font-family: 'Roboto', sans-serif;
        }
        .form-control, .form-control:focus {
            border-color: #e1e1e1;
        }
        .form-control, .btn {
            border-radius: 5px;
        }
        .password-change-form {
            width: 600px;
            margin: 0 auto;
            padding: 30px 0;
        }
        .password-change-form form {
            color: #999;
            border-radius: 5px;
            margin-bottom: 15px;
            background: #fff;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
            padding: 40px;
            transition: all 0.3s ease;
        }
        .password-change-form h2 {
            color: #333;
            font-weight: bold;
            margin-top: 0;
        }
        .password-change-form hr {
            margin: 0 -40px 20px;
        }
        .password-change-form .form-group {
            margin-bottom: 20px;
        }
        .password-change-form label {
            font-weight: normal;
            font-size: 13px;
        }
        .password-change-form .form-control {
            min-height: 38px;
            box-shadow: none !important;
            transition: border-color 0.3s ease;
        }
        .password-change-form .btn {
            font-size: 16px;
            font-weight: bold;
            background: #ff6f61;
            border: none;
            min-width: 140px;
            transition: background-color 0.3s ease;
        }
        .password-change-form .btn:hover, .password-change-form .btn:focus {
            background: #e55e50;
            outline: none;
        }
        .password-change-form .alert {
            margin-bottom: 20px;
        }
        body .btn {
            height: 40px;
            width: 200px;
            border-radius: 5px;
            font-size: 16px;
            font-weight: bold;
            background: #ff6f61;
            border: none;
            min-width: 140px;
            transition: background-color 0.3s ease;
            text-decoration: none;
            color: #e1e1e1;
        }
        body .btn:hover, body .btn:focus {
            background: #e55e50;
        }
        .messages {
            margin-top: 20px;
            list-style-type: none;
            padding: 0;
        }

        .messages li {
            background-color: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 6px;
        }

        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }
    </style>
</head>
<body>
    <span style="position: absolute; top: 20px; left: 20px;">
        <a href="/shop/"><button class="btn btn-primary" style="color: #ffffff;">Back to Homepage</button></a>
    </span>
    <div class="password-change-form">
        <form method="POST">
            {% csrf_token %}
            <h2>Change Password</h2>
            <p>Enter your current password and new password below.</p>
            <hr>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
            {{ form.as_p }}
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg">Change Password</button>
            </div>
        </form>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</body>
</html>

online-pharmacy/shop/templates/shop/contact.html
{% extends 'shop/style.html' %}
{% block title %} Contact Us {% endblock %}
{% block body %}
<main style="background-color: #f9f9f9; padding: 50px 0;">
    <div class="container">
        <h1 style="color: #2ec4b6; border-bottom: 3px solid #17a2b8; padding-bottom: 10px; margin-bottom: 20px; text-align: center;">Contact Us</h1>
        <div class="row justify-content-center">
            <div class="col-md-6 mb-4">
                <h2 style="color: #2ec4b6; border-bottom: 2px solid #17a2b8; padding-bottom: 10px; margin-bottom: 20px; text-align: center;">Send Us a Message</h2>
                <form>
                    <div class="form-group">
                        <label for="name">Your Name</label>
                        <input type="text" class="form-control" id="name">
                    </div>
                    <div class="form-group">
                        <label for="email">Your Email</label>
                        <input type="email" class="form-control" id="email">
                    </div>
                    <div class="form-group">
                        <label for="message">Message</label>
                        <textarea class="form-control" id="message" rows="5"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Send Message</button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

online-pharmacy/shop/templates/shop/nomatch.html
{% extends 'shop/style.html' %}

{% block title %} {{product.product_name}} {% endblock %}
{% block body %}
<br>
<h4 my="4" align="center">No Matching Product</h4>
{% endblock %}

online-pharmacy/shop/templates/shop/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body {
            color: #fff;
            background: linear-gradient(to right, #adf5ee, #0ba797);
            font-family: 'Roboto', sans-serif;
        }
        .form-control, .form-control:focus, .input-group-addon {
            border-color: #e1e1e1;
        }
        .form-control, .btn {
            border-radius: 5px;
        }
        .profile-form {
            width: 600px;
            margin: 0 auto;
            padding: 30px 0;
            animation: fadeIn 1s ease-in-out;
        }
        .profile-form form {
            color: #999;
            border-radius: 10px;
            margin-bottom: 15px;
            background: #f9f9f9;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
            padding: 40px;
            transition: all 0.3s ease;
        }
        .profile-form h2 {
            color: #333;
            font-weight: bold;
            margin-top: 0;
        }
        .profile-form hr {
            margin: 0 -40px 20px;
        }
        .profile-form .form-group {
            margin-bottom: 20px;
        }
        .profile-form label {
            font-weight: normal;
            font-size: 13px;
        }
        .profile-form .form-control {
            min-height: 38px;
            box-shadow: none !important;
            transition: border-color 0.3s ease;
            width: calc(100% - 42px); 
        }
        .profile-form .input-group-addon {
            width: 42px; 
            text-align: center;
            background-color: #f7f7f7;
        }
        .profile-form .btn {
            font-size: 16px;
            font-weight: bold;
            background: #ff6f61;
            border: none;
            min-width: 140px;
            transition: background-color 0.3s ease;
        }
        .profile-form .btn:hover, .profile-form .btn:focus {
            background: #e55e50;
            outline: none;
        }
        .profile-form a {
            color: #ff6f61;
            transition: color 0.3s ease;
        }
        .profile-form a:hover {
            text-decoration: none;
            color: #ff3f34;
        }
        .profile-form form a {
            color: #ff6f61;
            text-decoration: none;
        }
        .profile-form form a:hover {
            text-decoration: underline;
        }
        .profile-form .fa {
            font-size: 21px;
        }
        .profile-form .fa-paper-plane {
            font-size: 18px;
        }
        .profile-form .fa-check {
            color: #fff;
            left: 17px;
            top: 18px;
            font-size: 7px;
            position: absolute;
        }
        .login-btn {
            display: inline-block;
            padding: 7.5px 15px;
            margin-top: 10px;
            background-color: #ff6f61;
            color: #fff !important; 
            border: 2px solid #ff6f61;
            border-radius: 5px;
            font-weight: bold;
            text-decoration: none !important;
            transition: background-color 0.3s, border-color 0.3s !important;
        }
        .login-btn:hover {
            background-color: #e55e50;
            border-color: #e55e50;
            color: #fff;
            text-decoration: none;
        }
        .change-password-btn {
            display: inline-block;
            padding: 7.5px 15px;
            margin-top: 10px;
            background-color: #ff6f61;
            color: #fff !important; 
            border: 2px solid #ff6f61;
            border-radius: 5px;
            font-weight: bold;
            text-decoration: none !important;
            transition: background-color 0.3s, border-color 0.3s !important;
        }
        .change-password-btn:hover {
            background-color: #e55e50;
            border-color: #e55e50;
            color: #fff;
            text-decoration: none;
        }
        a{
            color: black;
            font-size: 0.9rem;
        }
        .messages {
            margin-top: 20px;
            list-style-type: none;
            padding: 0;
        }

        .messages li {
            background-color: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 6px;
        }

        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }
        body .btn {
            height: 40px;
            width: 200px;
            font-size: 16px;
            font-weight: bold;
            background: #ff6f61;
            border: none;
            min-width: 140px;
            transition: background-color 0.3s ease;
            text-decoration: none;
            color: #e1e1e1;
        }
        body .btn:hover, body .btn:focus {
            background: #e55e50;
        }
    </style>
</head>
<body>
    <span style="position:absolute; margin: 20px;">
        <a href="/shop/"><button class="btn btn-primary" style="color: #ffffff;">Back to Homepage</button></a>
    </span>
    <div class="profile-form">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>Update Profile</h2>
            <hr>
            <div class="form-group">
                <label for="id_username">Username</label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                    {{ u_form.username }}
                </div>
                {% if u_form.username.errors %}
                    <p class="text-danger">{{ u_form.username.errors }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_email">Email</label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-paper-plane"></i></span>
                    {{ u_form.email }}
                </div>
                {% if u_form.email.errors %}
                    <p class="text-danger">{{ u_form.email.errors }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_full_name">Full Name</label>
                <input type="text" name="full_name" class="form-control" id="id_full_name" value="{{ p_form.full_name.value }}">
                {% if p_form.full_name.errors %}
                    <p class="text-danger">{{ p_form.full_name.errors }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_address">Address</label>
                <input type="text" name="address" class="form-control" id="id_address" value="{{ p_form.address.value }}">
                {% if p_form.address.errors %}
                    <p class="text-danger">{{ p_form.address.errors }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_area">Area</label>
                <input type="text" name="area" class="form-control" id="id_area" value="{{ p_form.area.value }}">
                {% if p_form.area.errors %}
                    <p class="text-danger">{{ p_form.area.errors }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_contact_number">Contact Number</label>
                <input type="text" name="contact_number" class="form-control" id="id_contact_number" value="{{ p_form.contact_number.value }}">
                {% if p_form.contact_number.errors %}
                    <p class="text-danger">{{ p_form.contact_number.errors }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_image">Profile Image</label>
                {% if p_form.image.value %}
                    <!-- <img src="{{ p_form.image.value.url }}" alt="Profile Image" width="100" height="100"><br> -->
                {% endif %}
                {{ p_form.image }}
                {% if p_form.image.errors %}
                    <p class="text-danger">{{ p_form.image.errors }}</p>
                {% endif %}
            </div>
            <div style="display: flex; justify-content: space-between;">
                <div>
                    <button type="submit" class="btn btn-primary btn-lg">Update</button>
                </div>
                <div>
                    <a href="/shop/change_password" style="font-weight: 600;">Change Your Password</a>
                </div>
            </div>
        </form>

        {% if request.method == 'POST' and not u_form.username.errors and not u_form.email.errors and not p_form.image.errors %}
            <div class="text-center">
                <p>Your profile has been successfully updated.</p>
                <a class="login-btn" href="/shop/login">Login</a>
            </div>
        {% endif %}
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</body>
</html>